"""Wave $SPRINT coordinator — generated by new_sprint.py.

Sprint: lowcode-plugin-production-heal-$SPRINT-$DATE
Lanes: $LANES
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from scripts._coordinator_base import CoordinatorBase  # noqa: E402

SPRINT = "lowcode-plugin-production-heal-$SPRINT-$DATE"
REPORT_DIR = Path("reports") / SPRINT


def main() -> None:
    coord = CoordinatorBase(SPRINT, REPORT_DIR)

    # ── Lane 0: Coordinator setup ────────────────────────────────────────
    coord.setup_dirs(REPORT_DIR, [
        "coordinator", "taskcards",
    ])

    tasks = [
        {"id": f"W-$SPRINT-L0-01", "lane": "L0", "description": "Initialize coordinator"},
    ]
    coord.write_taskcards(SPRINT, tasks)
    coord.update_taskcard(SPRINT, f"W-$SPRINT-L0-01", "COMPLETE",
                          evidence_path="coordinator/execution-board.json")

    coord.write_lane_ledger(SPRINT, [{"lane": l, "status": "PENDING"} for l in "$LANES".split(",")])
    coord.write_execution_board(SPRINT, [{"lane": l, "status": "PENDING"} for l in "$LANES".split(",")])
    coord.write_hard_stop_conditions(SPRINT, [])

    board = coord.write_execution_board(SPRINT, [])
    print(f"Sprint {SPRINT} initialized. Board: {board}")


if __name__ == "__main__":
    main()
