// note/convert-one-to-word
// Canonical: https://products.aspose.net/note/convert-onenote-to-word/
// Package: Aspose.Note 24.12.0
// Note: Aspose.Note 24.12.0 SaveFormat does not include Docx/Doc.
// Best-match output: HTML (Word-compatible rich text format).
// Pattern: new Document() -> AppendChildLast -> Save(SaveFormat.Html)
using Aspose.Note;
using System;
using System.IO;

Directory.CreateDirectory("output");
string outputPath = Path.Combine("output", "output.html");

var doc = new Document();
var page = new Page();
var outline = new Outline();
var element = new OutlineElement();
var richText = new RichText()
{
    Text = "OneNote to Word Conversion Demo\n" +
           "This document was generated by Aspose.Note.\n" +
           "Saved as HTML (Word-compatible format) from OneNote source.\n" +
           "Section 1: Introduction to Aspose.Note\n" +
           "Section 2: Export to rich text format",
    ParagraphStyle = ParagraphStyle.Default
};
element.AppendChildLast(richText);
outline.AppendChildLast(element);
page.AppendChildLast(outline);
doc.AppendChildLast(page);
doc.Save(outputPath, SaveFormat.Html);
Console.WriteLine($"Note converted to HTML (Word-compatible): {outputPath} ({new FileInfo(outputPath).Length} bytes)");
