"""
Programmatic fixture generators for dry-run example packages.

Fixtures must be:
- Generated from first principles (no proprietary input files)
- Reproducible and deterministic
- Minimal (smallest valid file for each format)
- Annotated with provenance info
"""
import base64
import struct
import zlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


# ── Minimal valid PNG (1x1 white pixel) embedded as base64 ──────────────────
# Generated from PNG spec: signature + IHDR + IDAT + IEND chunks
_MINIMAL_1x1_WHITE_PNG_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwADhQGAWjR9awAAAABJRU5ErkJggg=="
)

# ── Minimal 40x12 white PNG (wider, for OCR use) ────────────────────────────
_MINIMAL_40x12_WHITE_PNG_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAMCAYAAAAhMsU7AAAAH0lEQVR42mNk+M9QDwAD"
    "hgGAWjR9awAAAABJRU5ErkJggg=="
)


@dataclass
class FixtureResult:
    fixture_type: str
    path: Optional[Path] = None
    size_bytes: int = 0
    strategy: str = "programmatic"
    description: str = ""
    provenance: dict = field(default_factory=dict)
    error: Optional[str] = None

    @property
    def success(self) -> bool:
        return self.error is None and self.path is not None and self.size_bytes > 0


def generate_minimal_png(dest: Path, width: int = 1, height: int = 1) -> FixtureResult:
    """Write a minimal valid PNG (white pixels) to dest."""
    if width == 1 and height == 1:
        data = base64.b64decode(_MINIMAL_1x1_WHITE_PNG_B64)
    elif width == 40 and height == 12:
        data = base64.b64decode(_MINIMAL_40x12_WHITE_PNG_B64)
    else:
        data = _build_png(width, height, fill=(255, 255, 255))
    dest.write_bytes(data)
    return FixtureResult(
        fixture_type="PNG",
        path=dest,
        size_bytes=len(data),
        strategy="programmatic",
        description=f"Minimal {width}x{height} white PNG",
        provenance={"source": "png_spec", "width": width, "height": height},
    )


def generate_barcode_png(dest: Path, value: str = "ASPOSE-TEST-2026") -> FixtureResult:
    """
    Generate a minimal barcode-like PNG fixture.
    This is a structural PNG (not a real barcode) for testing that the
    framework accepts PNG input. Actual barcode generation is done by
    Aspose.BarCode in the C# program itself.
    """
    # 200x60 white PNG with vertical black stripes (simulates barcode appearance)
    width, height = 200, 60
    data = _build_barcode_png(width, height)
    dest.write_bytes(data)
    return FixtureResult(
        fixture_type="PNG",
        path=dest,
        size_bytes=len(data),
        strategy="programmatic",
        description=f"Barcode-like PNG fixture ({width}x{height})",
        provenance={"source": "png_spec", "value": value, "note": "structural fixture"},
    )


def generate_bmp_fixture(dest: Path, width: int = 100, height: int = 100,
                         r: int = 65, g: int = 105, b: int = 225) -> FixtureResult:
    """
    Generate a minimal BMP file with solid color fill.
    BMP format is simple enough to generate from pure Python without PIL.
    """
    data = _build_bmp(width, height, r, g, b)
    dest.write_bytes(data)
    return FixtureResult(
        fixture_type="BMP",
        path=dest,
        size_bytes=len(data),
        strategy="programmatic",
        description=f"Solid-color BMP {width}x{height} RGB({r},{g},{b})",
        provenance={"source": "bmp_spec", "width": width, "height": height},
    )


def generate_svg_fixture(dest: Optional[Path] = None, title: str = "Test SVG") -> FixtureResult:
    """Generate a minimal SVG string or file."""
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="200" height="150">'
        f'<rect width="200" height="150" fill="#f0f8ff"/>'
        f'<rect x="20" y="20" width="160" height="110" rx="8" fill="#4a90d9"/>'
        f'<text x="100" y="85" text-anchor="middle" font-size="18" fill="white">{title}</text>'
        f"</svg>"
    )
    if dest:
        dest.write_text(svg, encoding="utf-8")
        size = len(svg.encode("utf-8"))
    else:
        size = len(svg.encode("utf-8"))
    return FixtureResult(
        fixture_type="SVG",
        path=dest,
        size_bytes=size,
        strategy="inline",
        description=f"Minimal SVG inline fixture: '{title}'",
        provenance={"source": "inline_template"},
    )


def generate_html_fixture(dest: Optional[Path] = None, title: str = "Test Page") -> FixtureResult:
    """Generate a minimal HTML string or file."""
    html = (
        f"<!DOCTYPE html><html><head><title>{title}</title>"
        f"<style>body{{font-family:Arial;margin:30px;}}h1{{color:#2c5f8a;}}</style></head>"
        f"<body><h1>{title}</h1><p>Generated by fixture factory.</p>"
        f"<ul><li>Item 1</li><li>Item 2</li><li>Item 3</li></ul></body></html>"
    )
    if dest:
        dest.write_text(html, encoding="utf-8")
        size = len(html.encode("utf-8"))
    else:
        size = len(html.encode("utf-8"))
    return FixtureResult(
        fixture_type="HTML",
        path=dest,
        size_bytes=size,
        strategy="inline",
        description=f"Minimal HTML fixture: '{title}'",
        provenance={"source": "inline_template"},
    )


def generate_zip_fixture(dest: Path, entries: Optional[list] = None) -> FixtureResult:
    """Generate a minimal ZIP archive containing text entries."""
    import zipfile
    entries = entries or [
        ("file1.txt", b"Hello from fixture factory.\n"),
        ("data/file2.txt", b"Second fixture entry.\n"),
    ]
    with zipfile.ZipFile(dest, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, content in entries:
            zf.writestr(name, content)
    size = dest.stat().st_size
    return FixtureResult(
        fixture_type="ZIP",
        path=dest,
        size_bytes=size,
        strategy="programmatic",
        description=f"ZIP fixture with {len(entries)} entries",
        provenance={"source": "zipfile_module", "entries": [e[0] for e in entries]},
    )


# ── Internal PNG builder ─────────────────────────────────────────────────────

def _png_chunk(chunk_type: bytes, data: bytes) -> bytes:
    length = struct.pack(">I", len(data))
    crc = struct.pack(">I", zlib.crc32(chunk_type + data) & 0xFFFFFFFF)
    return length + chunk_type + data + crc


def _build_png(width: int, height: int, fill: tuple = (255, 255, 255)) -> bytes:
    """Build a minimal RGB PNG from scratch."""
    signature = b"\x89PNG\r\n\x1a\n"
    # IHDR: width, height, bit_depth=8, color_type=2 (RGB), compress=0, filter=0, interlace=0
    ihdr_data = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    ihdr = _png_chunk(b"IHDR", ihdr_data)
    # IDAT: raw scanlines with filter byte 0
    raw_rows = b""
    for _ in range(height):
        row = b"\x00" + bytes(fill) * width
        raw_rows += row
    compressed = zlib.compress(raw_rows)
    idat = _png_chunk(b"IDAT", compressed)
    iend = _png_chunk(b"IEND", b"")
    return signature + ihdr + idat + iend


def _build_barcode_png(width: int = 200, height: int = 60) -> bytes:
    """Build a PNG with vertical black/white stripes (barcode visual)."""
    signature = b"\x89PNG\r\n\x1a\n"
    ihdr_data = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    ihdr = _png_chunk(b"IHDR", ihdr_data)
    raw_rows = b""
    for y in range(height):
        row = b"\x00"
        for x in range(width):
            # Alternate black/white stripes every 4 pixels
            if (x // 4) % 3 == 1:
                row += b"\x00\x00\x00"  # black
            else:
                row += b"\xFF\xFF\xFF"  # white
        raw_rows += row
    compressed = zlib.compress(raw_rows)
    idat = _png_chunk(b"IDAT", compressed)
    iend = _png_chunk(b"IEND", b"")
    return signature + ihdr + idat + iend


def _build_bmp(width: int, height: int, r: int, g: int, b: int) -> bytes:
    """Build a minimal BMP file with solid fill color."""
    row_size = ((width * 3 + 3) // 4) * 4  # padded to 4 bytes
    pixel_data_size = row_size * height
    file_size = 54 + pixel_data_size
    # BMP file header (14 bytes)
    file_header = struct.pack("<2sIHHI", b"BM", file_size, 0, 0, 54)
    # DIB header (BITMAPINFOHEADER, 40 bytes)
    dib = struct.pack("<IiiHHIIiiII", 40, width, -height, 1, 24, 0, pixel_data_size, 2835, 2835, 0, 0)
    # Pixel data
    row = bytes([b, g, r]) * width  # BMP is BGR
    padding = b"\x00" * (row_size - width * 3)
    pixel_data = (row + padding) * height
    return file_header + dib + pixel_data
