"""
Programmatic fixture generators for dry-run example packages.

Fixtures must be:
- Generated from first principles (no proprietary input files)
- Reproducible and deterministic
- Minimal (smallest valid file for each format)
- Annotated with provenance info
"""
import base64
import struct
import zlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


# ── Minimal valid PNG (1x1 white pixel) embedded as base64 ──────────────────
# Generated from PNG spec: signature + IHDR + IDAT + IEND chunks
_MINIMAL_1x1_WHITE_PNG_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwADhQGAWjR9awAAAABJRU5ErkJggg=="
)

# ── Minimal 40x12 white PNG (wider, for OCR use) ────────────────────────────
_MINIMAL_40x12_WHITE_PNG_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAMCAYAAAAhMsU7AAAAH0lEQVR42mNk+M9QDwAD"
    "hgGAWjR9awAAAABJRU5ErkJggg=="
)


@dataclass
class FixtureResult:
    fixture_type: str
    path: Optional[Path] = None
    size_bytes: int = 0
    strategy: str = "programmatic"
    description: str = ""
    provenance: dict = field(default_factory=dict)
    error: Optional[str] = None

    @property
    def success(self) -> bool:
        return self.error is None and self.path is not None and self.size_bytes > 0


def generate_minimal_png(dest: Path, width: int = 1, height: int = 1) -> FixtureResult:
    """Write a minimal valid PNG (white pixels) to dest."""
    if width == 1 and height == 1:
        data = base64.b64decode(_MINIMAL_1x1_WHITE_PNG_B64)
    elif width == 40 and height == 12:
        data = base64.b64decode(_MINIMAL_40x12_WHITE_PNG_B64)
    else:
        data = _build_png(width, height, fill=(255, 255, 255))
    dest.write_bytes(data)
    return FixtureResult(
        fixture_type="PNG",
        path=dest,
        size_bytes=len(data),
        strategy="programmatic",
        description=f"Minimal {width}x{height} white PNG",
        provenance={"source": "png_spec", "width": width, "height": height},
    )


def generate_barcode_png(dest: Path, value: str = "ASPOSE-TEST-2026") -> FixtureResult:
    """
    Generate a minimal barcode-like PNG fixture.
    This is a structural PNG (not a real barcode) for testing that the
    framework accepts PNG input. Actual barcode generation is done by
    Aspose.BarCode in the C# program itself.
    """
    # 200x60 white PNG with vertical black stripes (simulates barcode appearance)
    width, height = 200, 60
    data = _build_barcode_png(width, height)
    dest.write_bytes(data)
    return FixtureResult(
        fixture_type="PNG",
        path=dest,
        size_bytes=len(data),
        strategy="programmatic",
        description=f"Barcode-like PNG fixture ({width}x{height})",
        provenance={"source": "png_spec", "value": value, "note": "structural fixture"},
    )


def generate_bmp_fixture(dest: Path, width: int = 100, height: int = 100,
                         r: int = 65, g: int = 105, b: int = 225) -> FixtureResult:
    """
    Generate a minimal BMP file with solid color fill.
    BMP format is simple enough to generate from pure Python without PIL.
    """
    data = _build_bmp(width, height, r, g, b)
    dest.write_bytes(data)
    return FixtureResult(
        fixture_type="BMP",
        path=dest,
        size_bytes=len(data),
        strategy="programmatic",
        description=f"Solid-color BMP {width}x{height} RGB({r},{g},{b})",
        provenance={"source": "bmp_spec", "width": width, "height": height},
    )


def generate_svg_fixture(dest: Optional[Path] = None, title: str = "Test SVG") -> FixtureResult:
    """Generate a minimal SVG string or file."""
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="200" height="150">'
        f'<rect width="200" height="150" fill="#f0f8ff"/>'
        f'<rect x="20" y="20" width="160" height="110" rx="8" fill="#4a90d9"/>'
        f'<text x="100" y="85" text-anchor="middle" font-size="18" fill="white">{title}</text>'
        f"</svg>"
    )
    if dest:
        dest.write_text(svg, encoding="utf-8")
        size = len(svg.encode("utf-8"))
    else:
        size = len(svg.encode("utf-8"))
    return FixtureResult(
        fixture_type="SVG",
        path=dest,
        size_bytes=size,
        strategy="inline",
        description=f"Minimal SVG inline fixture: '{title}'",
        provenance={"source": "inline_template"},
    )


def generate_html_fixture(dest: Optional[Path] = None, title: str = "Test Page") -> FixtureResult:
    """Generate a minimal HTML string or file."""
    html = (
        f"<!DOCTYPE html><html><head><title>{title}</title>"
        f"<style>body{{font-family:Arial;margin:30px;}}h1{{color:#2c5f8a;}}</style></head>"
        f"<body><h1>{title}</h1><p>Generated by fixture factory.</p>"
        f"<ul><li>Item 1</li><li>Item 2</li><li>Item 3</li></ul></body></html>"
    )
    if dest:
        dest.write_text(html, encoding="utf-8")
        size = len(html.encode("utf-8"))
    else:
        size = len(html.encode("utf-8"))
    return FixtureResult(
        fixture_type="HTML",
        path=dest,
        size_bytes=size,
        strategy="inline",
        description=f"Minimal HTML fixture: '{title}'",
        provenance={"source": "inline_template"},
    )


def generate_geojson_fixture(dest: Optional[Path] = None) -> FixtureResult:
    """Generate a minimal GeoJSON FeatureCollection (point + polygon)."""
    geojson = (
        '{\n'
        '  "type": "FeatureCollection",\n'
        '  "features": [\n'
        '    {\n'
        '      "type": "Feature",\n'
        '      "geometry": {"type": "Point", "coordinates": [13.4050, 52.5200]},\n'
        '      "properties": {"name": "Berlin", "pop": 3645000}\n'
        '    },\n'
        '    {\n'
        '      "type": "Feature",\n'
        '      "geometry": {\n'
        '        "type": "Polygon",\n'
        '        "coordinates": [[[0.0,0.0],[1.0,0.0],[1.0,1.0],[0.0,1.0],[0.0,0.0]]]\n'
        '      },\n'
        '      "properties": {"name": "Unit Square", "area_km2": 1.0}\n'
        '    }\n'
        '  ]\n'
        '}'
    )
    if dest:
        dest.write_text(geojson, encoding="utf-8")
        size = len(geojson.encode("utf-8"))
    else:
        size = len(geojson.encode("utf-8"))
    return FixtureResult(
        fixture_type="GeoJSON",
        path=dest,
        size_bytes=size,
        strategy="inline",
        description="Minimal GeoJSON FeatureCollection (point + polygon)",
        provenance={"source": "inline_template", "features": 2},
    )


def generate_obj_fixture(dest: Optional[Path] = None, name: str = "unit_cube") -> FixtureResult:
    """Generate a minimal Wavefront OBJ file (unit cube, 8 vertices, 6 faces)."""
    obj = (
        f"# Minimal Wavefront OBJ — {name}\n"
        "# 8 vertices, 6 quad faces\n"
        "v 0 0 0\n"
        "v 1 0 0\n"
        "v 1 1 0\n"
        "v 0 1 0\n"
        "v 0 0 1\n"
        "v 1 0 1\n"
        "v 1 1 1\n"
        "v 0 1 1\n"
        "# faces (1-indexed)\n"
        "f 1 2 3 4\n"
        "f 5 6 7 8\n"
        "f 1 2 6 5\n"
        "f 3 4 8 7\n"
        "f 1 4 8 5\n"
        "f 2 3 7 6\n"
    )
    if dest:
        dest.write_text(obj, encoding="utf-8")
        size = len(obj.encode("utf-8"))
    else:
        size = len(obj.encode("utf-8"))
    return FixtureResult(
        fixture_type="OBJ",
        path=dest,
        size_bytes=size,
        strategy="inline",
        description=f"Minimal OBJ unit cube '{name}'",
        provenance={"source": "inline_template", "vertices": 8, "faces": 6},
    )


def generate_xbrl_fixture(dest: Optional[Path] = None) -> FixtureResult:
    """Generate a minimal XBRL instance document."""
    xbrl = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<xbrl xmlns="http://www.xbrl.org/2003/instance"\n'
        '      xmlns:xbrli="http://www.xbrl.org/2003/instance"\n'
        '      xmlns:link="http://www.xbrl.org/2003/linkbase"\n'
        '      xmlns:xlink="http://www.w3.org/1999/xlink"\n'
        '      xmlns:ifrs="http://xbrl.ifrs.org/taxonomy/2021-03-24/ifrs-full">\n'
        '  <link:schemaRef xlink:type="simple"\n'
        '    xlink:href="http://xbrl.ifrs.org/taxonomy/2021-03-24/ifrs-full"/>\n'
        '  <context id="ctx_fy2025">\n'
        '    <entity><identifier scheme="http://www.lei.org">TESTENTITY001</identifier></entity>\n'
        '    <period><startDate>2025-01-01</startDate><endDate>2025-12-31</endDate></period>\n'
        '  </context>\n'
        '  <ifrs:Revenue contextRef="ctx_fy2025" decimals="0" unitRef="USD">1500000</ifrs:Revenue>\n'
        '  <ifrs:ProfitLoss contextRef="ctx_fy2025" decimals="0" unitRef="USD">250000</ifrs:ProfitLoss>\n'
        '  <unit id="USD"><measure>iso4217:USD</measure></unit>\n'
        '</xbrl>\n'
    )
    if dest:
        dest.write_text(xbrl, encoding="utf-8")
        size = len(xbrl.encode("utf-8"))
    else:
        size = len(xbrl.encode("utf-8"))
    return FixtureResult(
        fixture_type="XBRL",
        path=dest,
        size_bytes=size,
        strategy="inline",
        description="Minimal XBRL instance document (IFRS, FY2025)",
        provenance={"source": "inline_template", "standard": "xbrl-2003"},
    )


def generate_ps_fixture(dest: Optional[Path] = None, title: str = "Test Document") -> FixtureResult:
    """Generate a minimal PostScript document."""
    ps = (
        "%!PS-Adobe-3.0\n"
        f"%%Title: {title}\n"
        "%%Creator: Aspose.Page Fixture Factory\n"
        "%%Pages: 1\n"
        "%%BoundingBox: 0 0 595 842\n"
        "%%EndComments\n"
        "%%Page: 1 1\n"
        "/Helvetica findfont 24 scalefont setfont\n"
        "72 750 moveto\n"
        f"({title}) show\n"
        "/Helvetica findfont 14 scalefont setfont\n"
        "72 720 moveto\n"
        "(Generated by Aspose.Page fixture factory.) show\n"
        "72 700 moveto\n"
        "(Minimal valid PostScript for conversion testing.) show\n"
        "showpage\n"
        "%%EOF\n"
    )
    if dest:
        dest.write_text(ps, encoding="utf-8")
        size = len(ps.encode("utf-8"))
    else:
        size = len(ps.encode("utf-8"))
    return FixtureResult(
        fixture_type="PS",
        path=dest,
        size_bytes=size,
        strategy="inline",
        description=f"Minimal PostScript document: '{title}'",
        provenance={"source": "inline_template", "pages": 1},
    )


def generate_note_xml_fixture(dest: Optional[Path] = None, title: str = "Test Note") -> FixtureResult:
    """Generate a minimal OneNote-compatible XML document fixture."""
    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<Document xmlns="http://aspose.com/note/1.0">\n'
        f'  <Title><Text>{title}</Text></Title>\n'
        '  <Page>\n'
        '    <Title><Text>First Page</Text></Title>\n'
        '    <Outline>\n'
        '      <OutlineElement>\n'
        f'        <RichText>This is a test note document: {title}. '
        'Generated by the fixture factory for dry-run testing.</RichText>\n'
        '      </OutlineElement>\n'
        '      <OutlineElement>\n'
        '        <RichText>Item 2: Programmatic fixture</RichText>\n'
        '      </OutlineElement>\n'
        '    </Outline>\n'
        '  </Page>\n'
        '</Document>\n'
    )
    if dest:
        dest.write_text(xml, encoding="utf-8")
        size = len(xml.encode("utf-8"))
    else:
        size = len(xml.encode("utf-8"))
    return FixtureResult(
        fixture_type="NOTE_XML",
        path=dest,
        size_bytes=size,
        strategy="inline",
        description=f"Minimal Note XML document: '{title}'",
        provenance={"source": "inline_template"},
    )


def generate_drawing_xml_fixture(dest: Optional[Path] = None) -> FixtureResult:
    """Generate a minimal Visio-compatible XML drawing fixture."""
    xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
        '<VisioDocument xmlns="urn:schemas-microsoft-com:office:visio"\n'
        '  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">\n'
        '  <DocumentProperties>\n'
        '    <Creator>Aspose.Diagram Fixture Factory</Creator>\n'
        '    <Description>Minimal Visio XML for dry-run testing</Description>\n'
        '  </DocumentProperties>\n'
        '  <Pages>\n'
        '    <Page ID="1" Name="Page-1">\n'
        '      <PageSheet LineStyle="0" FillStyle="0" TextStyle="0">\n'
        '        <PageProps><PageWidth F="Inh">8.5</PageWidth>'
        '<PageHeight F="Inh">11</PageHeight></PageProps>\n'
        '      </PageSheet>\n'
        '      <Shapes>\n'
        '        <Shape ID="1" Type="Shape" LineStyle="0" FillStyle="0" TextStyle="0">\n'
        '          <XForm><PinX>2</PinX><PinY>9</PinY><Width>2</Width><Height>1</Height></XForm>\n'
        '          <Text>Programmatic Shape</Text>\n'
        '        </Shape>\n'
        '      </Shapes>\n'
        '    </Page>\n'
        '  </Pages>\n'
        '</VisioDocument>\n'
    )
    if dest:
        dest.write_text(xml, encoding="utf-8")
        size = len(xml.encode("utf-8"))
    else:
        size = len(xml.encode("utf-8"))
    return FixtureResult(
        fixture_type="DRAWING_XML",
        path=dest,
        size_bytes=size,
        strategy="inline",
        description="Minimal Visio XML drawing fixture",
        provenance={"source": "inline_template", "shapes": 1},
    )


def generate_zip_fixture(dest: Path, entries: Optional[list] = None) -> FixtureResult:
    """Generate a minimal ZIP archive containing text entries."""
    import zipfile
    entries = entries or [
        ("file1.txt", b"Hello from fixture factory.\n"),
        ("data/file2.txt", b"Second fixture entry.\n"),
    ]
    with zipfile.ZipFile(dest, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, content in entries:
            zf.writestr(name, content)
    size = dest.stat().st_size
    return FixtureResult(
        fixture_type="ZIP",
        path=dest,
        size_bytes=size,
        strategy="programmatic",
        description=f"ZIP fixture with {len(entries)} entries",
        provenance={"source": "zipfile_module", "entries": [e[0] for e in entries]},
    )


def generate_eps_fixture(dest: Optional[Path] = None, title: str = "Aspose.Page EPS Demo") -> FixtureResult:
    """Generate a minimal valid EPS (Encapsulated PostScript) file."""
    eps_content = (
        f"%!PS-Adobe-3.0 EPSF-3.0\n"
        f"%%BoundingBox: 0 0 200 200\n"
        f"%%Title: {title}\n"
        f"%%Creator: lowcode-example-factory\n"
        f"%%CreationDate: 2026-06-05\n"
        f"%%EndComments\n"
        f"% Draw border\n"
        f"0.5 setlinewidth\n"
        f"10 10 moveto\n"
        f"190 10 lineto\n"
        f"190 190 lineto\n"
        f"10 190 lineto\n"
        f"closepath stroke\n"
        f"% Title text\n"
        f"/Helvetica findfont 14 scalefont setfont\n"
        f"20 160 moveto\n"
        f"({title}) show\n"
        f"% Description\n"
        f"/Helvetica findfont 10 scalefont setfont\n"
        f"20 130 moveto\n"
        f"(EPS fixture generated for dry-run testing) show\n"
        f"20 110 moveto\n"
        f"(Aspose.Page for .NET) show\n"
        f"%%EOF\n"
    )
    eps_bytes = eps_content.encode("ascii")
    if dest is not None:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(eps_bytes)
    return FixtureResult(
        fixture_type="EPS",
        path=dest,
        size_bytes=len(eps_bytes),
        strategy="inline",
        description=f"Minimal EPS 200x200 with text and border: {title}",
        provenance={"source": "inline_template", "bounding_box": "0 0 200 200", "format": "EPS-3.0"},
    )


def generate_psd_fixture(dest: Optional[Path] = None, width: int = 8, height: int = 8) -> FixtureResult:
    """Generate a minimal valid PSD (Photoshop Document) file from binary spec.

    Structure: Header + Color Mode Data (empty) + Image Resources (empty)
    + Layer/Mask Info (empty) + Image Data (raw, white pixels).
    """
    # Header (26 bytes)
    magic = b"8BPS"
    version = struct.pack(">H", 1)          # version 1 = PSD
    reserved = b"\x00" * 6
    channels = struct.pack(">H", 3)         # 3 channels = RGB
    h_bytes = struct.pack(">I", height)
    w_bytes = struct.pack(">I", width)
    bit_depth = struct.pack(">H", 8)        # 8-bit per channel
    color_mode = struct.pack(">H", 3)       # 3 = RGB
    header = magic + version + reserved + channels + h_bytes + w_bytes + bit_depth + color_mode

    color_mode_data = struct.pack(">I", 0)  # empty section
    image_resources = struct.pack(">I", 0)  # empty section
    layer_mask_info = struct.pack(">I", 0)  # empty section

    # Image data: compression=0 (raw), then all channel data in planar format
    compression = struct.pack(">H", 0)
    # White pixels: 0xFF for every pixel in every channel
    pixels_per_channel = width * height
    channel_data = bytes([0xFF]) * pixels_per_channel
    image_data = compression + channel_data * 3  # R, G, B channels

    psd_bytes = header + color_mode_data + image_resources + layer_mask_info + image_data

    if dest is not None:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(psd_bytes)
    return FixtureResult(
        fixture_type="PSD",
        path=dest,
        size_bytes=len(psd_bytes),
        strategy="programmatic",
        description=f"Minimal PSD {width}x{height} RGB white, binary-constructed",
        provenance={"width": width, "height": height, "channels": 3, "bit_depth": 8, "color_mode": "RGB"},
    )


def generate_rich_geojson_fixture(dest: Optional[Path] = None) -> FixtureResult:
    """Generate a richer GeoJSON FeatureCollection with 5 features and attributes.

    Includes Point, LineString, Polygon, MultiPoint, and MultiPolygon geometry types.
    """
    import json as _json
    feature_collection = {
        "type": "FeatureCollection",
        "features": [
            {
                "type": "Feature",
                "geometry": {"type": "Point", "coordinates": [-122.4194, 37.7749]},
                "properties": {"name": "San Francisco", "population": 873965, "country": "USA"},
            },
            {
                "type": "Feature",
                "geometry": {
                    "type": "LineString",
                    "coordinates": [[-122.4194, 37.7749], [-118.2437, 34.0522], [-87.6298, 41.8781]],
                },
                "properties": {"name": "US Route", "distance_km": 3600, "type": "highway"},
            },
            {
                "type": "Feature",
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [[
                        [-122.5, 37.7], [-122.3, 37.7], [-122.3, 37.9],
                        [-122.5, 37.9], [-122.5, 37.7],
                    ]],
                },
                "properties": {"name": "Bay Area Region", "area_km2": 400, "land_use": "urban"},
            },
            {
                "type": "Feature",
                "geometry": {
                    "type": "MultiPoint",
                    "coordinates": [[-73.9857, 40.7484], [-0.1276, 51.5074], [2.3522, 48.8566]],
                },
                "properties": {"name": "World Cities", "category": "major_city"},
            },
            {
                "type": "Feature",
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [[
                        [151.2093, -33.8688], [151.3, -33.8], [151.3, -33.9],
                        [151.1, -33.95], [151.2093, -33.8688],
                    ]],
                },
                "properties": {"name": "Sydney Metro", "area_km2": 200, "timezone": "AEST"},
            },
        ],
    }
    content = _json.dumps(feature_collection, indent=2).encode("utf-8")
    if dest is not None:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(content)
    return FixtureResult(
        fixture_type="RICH_GEOJSON",
        path=dest,
        size_bytes=len(content),
        strategy="inline",
        description="Rich GeoJSON FeatureCollection: 5 features, mixed geometry types, attributes",
        provenance={"features": 5, "geometry_types": ["Point", "LineString", "Polygon", "MultiPoint"], "has_attributes": True},
    )


def generate_latex_fixture(dest: Optional[Path] = None, title: str = "Aspose.TeX Demo") -> FixtureResult:
    """Generate a minimal valid LaTeX source file (.tex)."""
    latex_content = (
        r"\documentclass{minimal}" + "\n"
        r"\begin{document}" + "\n"
        f"\\textbf{{{title}}}\\\\\n"
        r"This document was compiled from LaTeX source" + "\n"
        r"using Aspose.TeX for .NET.\\" + "\n"
        r"Date: 2026-06-05\\" + "\n"
        r"\end{document}" + "\n"
    )
    tex_bytes = latex_content.encode("utf-8")
    if dest is not None:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(tex_bytes)
    return FixtureResult(
        fixture_type="LATEX",
        path=dest,
        size_bytes=len(tex_bytes),
        strategy="inline",
        description=f"Minimal LaTeX document: {title}",
        provenance={"source": "inline_template", "document_class": "minimal"},
    )


# ── Internal PNG builder ─────────────────────────────────────────────────────

def _png_chunk(chunk_type: bytes, data: bytes) -> bytes:
    length = struct.pack(">I", len(data))
    crc = struct.pack(">I", zlib.crc32(chunk_type + data) & 0xFFFFFFFF)
    return length + chunk_type + data + crc


def _build_png(width: int, height: int, fill: tuple = (255, 255, 255)) -> bytes:
    """Build a minimal RGB PNG from scratch."""
    signature = b"\x89PNG\r\n\x1a\n"
    # IHDR: width, height, bit_depth=8, color_type=2 (RGB), compress=0, filter=0, interlace=0
    ihdr_data = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    ihdr = _png_chunk(b"IHDR", ihdr_data)
    # IDAT: raw scanlines with filter byte 0
    raw_rows = b""
    for _ in range(height):
        row = b"\x00" + bytes(fill) * width
        raw_rows += row
    compressed = zlib.compress(raw_rows)
    idat = _png_chunk(b"IDAT", compressed)
    iend = _png_chunk(b"IEND", b"")
    return signature + ihdr + idat + iend


def _build_barcode_png(width: int = 200, height: int = 60) -> bytes:
    """Build a PNG with vertical black/white stripes (barcode visual)."""
    signature = b"\x89PNG\r\n\x1a\n"
    ihdr_data = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    ihdr = _png_chunk(b"IHDR", ihdr_data)
    raw_rows = b""
    for y in range(height):
        row = b"\x00"
        for x in range(width):
            # Alternate black/white stripes every 4 pixels
            if (x // 4) % 3 == 1:
                row += b"\x00\x00\x00"  # black
            else:
                row += b"\xFF\xFF\xFF"  # white
        raw_rows += row
    compressed = zlib.compress(raw_rows)
    idat = _png_chunk(b"IDAT", compressed)
    iend = _png_chunk(b"IEND", b"")
    return signature + ihdr + idat + iend


def _build_bmp(width: int, height: int, r: int, g: int, b: int) -> bytes:
    """Build a minimal BMP file with solid fill color."""
    row_size = ((width * 3 + 3) // 4) * 4  # padded to 4 bytes
    pixel_data_size = row_size * height
    file_size = 54 + pixel_data_size
    # BMP file header (14 bytes)
    file_header = struct.pack("<2sIHHI", b"BM", file_size, 0, 0, 54)
    # DIB header (BITMAPINFOHEADER, 40 bytes)
    dib = struct.pack("<IiiHHIIiiII", 40, width, -height, 1, 24, 0, pixel_data_size, 2835, 2835, 0, 0)
    # Pixel data
    row = bytes([b, g, r]) * width  # BMP is BGR
    padding = b"\x00" * (row_size - width * 3)
    pixel_data = (row + padding) * height
    return file_header + dib + pixel_data
