// note/convert-one-to-image
// Canonical: https://products.aspose.net/note/convert-onenote-to-image/
// Package: Aspose.Note 24.12.0
// Pattern: new Document() -> AppendChildLast -> Save(SaveFormat.Png)
using Aspose.Note;
using System;
using System.IO;

Directory.CreateDirectory("output");
string outputPath = Path.Combine("output", "output.png");

var doc = new Document();
var page = new Page();
var outline = new Outline();
var element = new OutlineElement();
var richText = new RichText()
{
    Text = "OneNote to Image Conversion Demo\n" +
           "This page was generated by Aspose.Note and exported as PNG.\n" +
           "Image export preserves page layout and text content.",
    ParagraphStyle = ParagraphStyle.Default
};
element.AppendChildLast(richText);
outline.AppendChildLast(element);
page.AppendChildLast(outline);
doc.AppendChildLast(page);
doc.Save(outputPath, SaveFormat.Png);
Console.WriteLine($"Note converted to Image: {outputPath} ({new FileInfo(outputPath).Length} bytes)");
