// html/convert-html-to-pdf
// Canonical: https://products.aspose.net/html/html-to-pdf-converter/
// Package: Aspose.HTML 24.12.0
// Pattern: Converter.ConvertHTML(string, baseUri, PdfSaveOptions, outputPath)
using Aspose.Html;
using Aspose.Html.Converters;
using Aspose.Html.Saving;
using System;
using System.IO;

Directory.CreateDirectory("output");
string outputPath = Path.Combine("output", "output.pdf");

string htmlContent =
    "<!DOCTYPE html><html><head><title>Aspose.HTML Demo</title>" +
    "<style>body{font-family:Arial,sans-serif;margin:40px;}" +
    "h1{color:#2c5f8a;}table{border-collapse:collapse;width:100%;}" +
    "td,th{border:1px solid #ccc;padding:8px;}</style></head><body>" +
    "<h1>HTML to PDF Conversion</h1>" +
    "<p>Generated by Aspose.HTML for .NET on 2026-06-05.</p>" +
    "<table><tr><th>Feature</th><th>Status</th></tr>" +
    "<tr><td>HTML parsing</td><td>Supported</td></tr>" +
    "<tr><td>CSS styling</td><td>Supported</td></tr>" +
    "<tr><td>PDF output</td><td>Supported</td></tr></table>" +
    "</body></html>";

Converter.ConvertHTML(htmlContent, ".", new PdfSaveOptions(), outputPath);
Console.WriteLine($"PDF saved: {outputPath} ({new FileInfo(outputPath).Length} bytes)");
