using System;
using System.IO;
using System.Threading.Tasks;
using Aspose.Email.LowCode;

class Program
{
    static async Task Main(string[] args)
    {
        // Prepare temporary directories
        string baseDir = Path.Combine(Path.GetTempPath(), "LowCodeDemo");
        string inputDir = Path.Combine(baseDir, "input");
        string outputDir = Path.Combine(baseDir, "output");
        Directory.CreateDirectory(inputDir);
        Directory.CreateDirectory(outputDir);

        // Create input .eml file using RFC 2822 format
        string inputPath = Path.Combine(inputDir, "input.eml");
        string emlContent =
            "From: sender@example.com\r\n" +
            "To: recipient@example.com\r\n" +
            "Subject: Test Email\r\n" +
            "Content-Type: text/plain; charset=utf-8\r\n" +
            "\r\n" +
            "This is a test email generated by Aspose.Email.";
        File.WriteAllText(inputPath, emlContent);

        // Validate input file exists
        if (!File.Exists(inputPath))
            throw new FileNotFoundException("Input .eml file was not created.", inputPath);

        // Prepare LowCode components
        var outputHandler = new FolderOutputHandler(outputDir);
        var stream = new MemoryStream(File.ReadAllBytes(inputPath));
        string fileName = Path.GetFileName(inputPath);

        // Perform conversion to HTML
        await Converter.ConvertToHtml(stream, fileName, outputHandler);

        // Validate output file exists
        string outputPath = Path.Combine(outputDir, "input.html");
        if (!File.Exists(outputPath))
            throw new FileNotFoundException("Conversion did not produce the expected HTML file.", outputPath);

        // Deterministic success output
        Console.WriteLine($"Conversion succeeded. Output file: {outputPath}");
    }
}