"""Build PR content for publishing validated examples."""

from __future__ import annotations

import logging
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class PRContent:
    """Content for a GitHub PR."""
    title: str
    body: str
    branch: str
    labels: list[str]


def build_pr(
    *,
    family: str,
    run_id: str,
    examples_count: int,
    package_version: str,
) -> PRContent:
    """Build PR title and body.

    Args:
        family: Family name.
        run_id: Run identifier.
        examples_count: Number of examples included.
        package_version: NuGet package version.

    Returns:
        PRContent with title, body, branch, labels.
    """
    title = f"feat({family}): add {examples_count} plugin examples (v{package_version})"

    body = f"""## Plugin Examples — {family}

**Package:** Aspose.{family.capitalize()} v{package_version}
**Run ID:** {run_id}
**Examples:** {examples_count}

### Evidence

- Source-of-truth proof verified
- All examples compiled and run successfully
- Output validation passed
- Example-reviewer gate checked

### Generated by

Pipeline: `lowcode-example-generator`
"""

    return PRContent(
        title=title,
        body=body,
        branch=f"pipeline/{run_id}/{family}",
        labels=["automated", "plugin-examples", family],
    )
