"""Build PR content for publishing validated examples."""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


@dataclass
class PRContent:
    """Content for a GitHub PR."""
    title: str
    body: str
    branch: str
    labels: list[str] = field(default_factory=list)


def build_pr(
    *,
    family: str,
    run_id: str,
    examples_count: int,
    package_version: str,
    examples_list: list[str] | None = None,
    excluded_scenarios: list[str] | None = None,
    gate_verdict: str = "PR_DRY_RUN_READY",
    reviewer_passed: bool = True,
) -> PRContent:
    """Build PR title and body with full evidence references.

    Args:
        family: Family name (e.g. 'cells', 'words').
        run_id: Run identifier (used for branch name generation).
        examples_count: Number of examples included.
        package_version: NuGet package version string.
        examples_list: Optional list of included example names for body.
        excluded_scenarios: Optional list of excluded scenario names/reasons.
        gate_verdict: Gate verdict string (default: PR_DRY_RUN_READY).
        reviewer_passed: Whether the example reviewer gate passed.

    Returns:
        PRContent with title, body, branch, labels.
    """
    family_cap = family.capitalize()
    title = (
        f"Add verified Aspose.{family_cap} LowCode examples for .NET controlled pilot"
    )

    # Build included examples section
    if examples_list:
        examples_lines = "\n".join(f"- `{ex}`" for ex in examples_list)
    else:
        examples_lines = f"- {examples_count} examples (see package for details)"

    # Build excluded scenarios section
    if excluded_scenarios:
        excluded_lines = "\n".join(f"- {s}" for s in excluded_scenarios)
    else:
        excluded_lines = "- None in this controlled pilot scope"

    reviewer_result = "PASSED" if reviewer_passed else "FAILED"

    body = f"""## Scope

This PR adds {examples_count} verified Aspose.{family_cap} LowCode examples for .NET.
All examples were generated by the automated pipeline and validated through the full
build + runtime + reviewer gate.

**DO NOT MERGE without human review of the examples.**

---

## Package

**NuGet Package:** `Aspose.{family_cap}` v{package_version}
**Target Framework:** `net8.0`
**Run ID:** `{run_id}`

---

## Included Examples

{examples_lines}

---

## Excluded Scenarios

{excluded_lines}

---

## Validation Summary

| Stage | Result |
|---|---|
| Source-of-truth proof | PASS |
| Example generation | PASS |
| dotnet build | PASS |
| dotnet runtime | PASS |
| Output validation | PASS |
| Example reviewer gate | {reviewer_result} |
| Gate verdict | `{gate_verdict}` |

---

## Reviewer Result

Gate verdict: `{gate_verdict}`
Example reviewer: {reviewer_result}

---

## Source-of-Truth Evidence

- `workspace/verification/latest/{family}-source-of-truth-proof.json` — NuGet reflection proof
- `workspace/verification/latest/validation-results.json` — build and runtime results
- `workspace/verification/latest/example-gate-results.json` — per-example gate results
- `workspace/verification/latest/gate-results.json` — overall gate verdict
- `workspace/verification/latest/publish-permission-probe.json` — push permissions confirmed

---

## Generated By

Pipeline: `lowcode-example-generator`
No manual edits. LLM proposed — compiler/runtime/reviewer approved.

---

## Merge Instructions

**Do not merge automatically.** Human review required:
1. Review each example for correctness
2. Confirm package version is current
3. Approve PR on GitHub
4. Merge only after explicit approval
"""

    return PRContent(
        title=title,
        body=body,
        branch=f"plugin-examples/{family}/{run_id}",
        labels=["automated", "plugin-examples", family],
    )
