"""Build PR content for publishing validated examples."""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

# PR scope types — ordered by completeness level
PR_SCOPE_PARTIAL_CANARY = "PARTIAL_CANARY"
PR_SCOPE_PILOT_COMPLETE = "PILOT_COMPLETE"
PR_SCOPE_FAMILY_COMPLETE = "FAMILY_COMPLETE"


def compute_pr_scope_type(
    family: str,
    denominator: dict,
    published_count: int,
) -> str:
    """Compute the PR scope type from denominator and published count.

    Returns one of: PARTIAL_CANARY, PILOT_COMPLETE, FAMILY_COMPLETE.

    Words guard: If workflow_root_types is null, FAMILY_COMPLETE is never returned
    because the full SOT classification has not been completed.
    """
    workflow_root_count = denominator.get("workflow_root_types")
    pilot_allowed = denominator.get("allowed_pilot_count")

    # Cannot be FAMILY_COMPLETE if workflow_root_count is unknown
    if workflow_root_count is not None and published_count >= workflow_root_count > 0:
        return PR_SCOPE_FAMILY_COMPLETE

    if pilot_allowed is not None and published_count >= pilot_allowed > 0:
        return PR_SCOPE_PILOT_COMPLETE

    return PR_SCOPE_PARTIAL_CANARY


@dataclass
class PRContent:
    """Content for a GitHub PR."""

    title: str
    body: str
    branch: str
    labels: list[str] = field(default_factory=list)
    pr_scope_type: str = "PARTIAL_CANARY"
    denominator_total: int | None = None
    denominator_remaining: int | None = None


def build_pr(
    *,
    family: str,
    run_id: str,
    examples_count: int,
    package_version: str,
    examples_list: list[str] | None = None,
    excluded_scenarios: list[str] | None = None,
    gate_verdict: str = "PR_DRY_RUN_READY",
    reviewer_passed: bool = True,
    pr_scope_type: str = "PARTIAL_CANARY",
    denominator_total: int | None = None,
    denominator_remaining: int | None = None,
) -> PRContent:
    """Build PR title and body with full evidence references.

    Args:
        family: Family name (e.g. 'cells', 'words').
        run_id: Run identifier (used for branch name generation).
        examples_count: Number of examples included.
        package_version: NuGet package version string.
        examples_list: Optional list of included example names for body.
        excluded_scenarios: Optional list of excluded scenario names/reasons.
        gate_verdict: Gate verdict string (default: PR_DRY_RUN_READY).
        reviewer_passed: Whether the example reviewer gate passed.

    Returns:
        PRContent with title, body, branch, labels.
    """
    family_cap = family.capitalize()
    title = f"Add verified Aspose.{family_cap} LowCode examples for .NET controlled pilot"

    # Build included examples section
    if examples_list:
        examples_lines = "\n".join(f"- `{ex}`" for ex in examples_list)
    else:
        examples_lines = f"- {examples_count} examples (see package for details)"

    # Build excluded scenarios section
    if excluded_scenarios:
        excluded_lines = "\n".join(f"- {s}" for s in excluded_scenarios)
    else:
        excluded_lines = "- None in this controlled pilot scope"

    reviewer_result = "PASSED" if reviewer_passed else "FAILED"

    # Build coverage section
    if denominator_total is not None:
        if denominator_remaining is not None and denominator_remaining > 0:
            coverage_note = (
                f"**PR scope:** `{pr_scope_type}`  \n"
                f"**Pilot coverage:** {examples_count}/{denominator_total} types  \n"
                f"**Remaining denominator:** {denominator_remaining} types not yet published  \n"
            )
        else:
            coverage_note = (
                f"**PR scope:** `{pr_scope_type}`  \n"
                f"**Coverage:** {examples_count}/{denominator_total} types — pilot complete  \n"
            )
        coverage_section = f"\n## Coverage\n\n{coverage_note}\n---\n"
    else:
        coverage_section = ""

    body = f"""## Scope

This PR adds {examples_count} verified Aspose.{family_cap} LowCode examples for .NET.
All examples were generated by the automated pipeline and validated through the full
build + runtime + reviewer gate.

**DO NOT MERGE without human review of the examples.**

---
{coverage_section}
## Package

**NuGet Package:** `Aspose.{family_cap}` v{package_version}
**Target Framework:** `net8.0`
**Run ID:** `{run_id}`

---

## Included Examples

{examples_lines}

---

## Excluded Scenarios

{excluded_lines}

---

## Validation Summary

| Stage | Result |
|---|---|
| Source-of-truth proof | PASS |
| Example generation | PASS |
| dotnet build | PASS |
| dotnet runtime | PASS |
| Output validation | PASS |
| Example reviewer gate | {reviewer_result} |
| Gate verdict | `{gate_verdict}` |

---

## Reviewer Result

Gate verdict: `{gate_verdict}`
Example reviewer: {reviewer_result}

---

## Source-of-Truth Evidence

- `workspace/verification/latest/{family}-source-of-truth-proof.json` — NuGet reflection proof
- `workspace/verification/latest/validation-results.json` — build and runtime results
- `workspace/verification/latest/example-gate-results.json` — per-example gate results
- `workspace/verification/latest/gate-results.json` — overall gate verdict
- `workspace/verification/latest/publish-permission-probe.json` — push permissions confirmed

---

## Generated By

Pipeline: `lowcode-example-generator`
No manual edits. LLM proposed — compiler/runtime/reviewer approved.

---

## Merge Instructions

**Do not merge automatically.** Human review required:
1. Review each example for correctness
2. Confirm package version is current
3. Approve PR on GitHub
4. Merge only after explicit approval
"""

    return PRContent(
        title=title,
        body=body,
        branch=f"plugin-examples/{family}/{run_id}",
        labels=["automated", "plugin-examples", family],
        pr_scope_type=pr_scope_type,
        denominator_total=denominator_total,
        denominator_remaining=denominator_remaining,
    )


def build_nonlowcode_pr(
    *,
    family: str,
    wave: str,
    examples_count: int,
    package_version: str,
    examples_list: list[str] | None = None,
) -> PRContent:
    """Build PR content for non-LowCode plugin examples.

    Produces the `feat(plugins):` title prefix and `lowcode/wave*/{family}-plugin-examples`
    branch name required for non-LowCode publication (Lane F-6).

    Args:
        family: Family name (e.g. 'barcode', 'cad').
        wave: Wave identifier (e.g. 'wave25').
        examples_count: Number of plugin packages included.
        package_version: NuGet package version string.
        examples_list: Optional list of example slugs for PR body.

    Returns:
        PRContent with feat(plugins): title and lowcode/wave* branch.
    """
    family_cap = family.capitalize()
    title = f"feat(plugins): add Aspose.{family_cap} plugin examples ({examples_count} packages)"
    branch = f"lowcode/{wave}/{family}-plugin-examples"

    if examples_list:
        examples_lines = "\n".join(f"- `{ex}`" for ex in examples_list)
    else:
        examples_lines = f"- {examples_count} packages (see examples/ directory)"

    body = f"""## Scope

This PR adds {examples_count} verified Aspose.{family_cap} plugin examples for .NET.
All examples were generated by the automated pipeline (non-LowCode capability registry path)
and validated through the full build + runtime + reviewer gate.

---

## Package

**NuGet Package:** `Aspose.{family_cap}` v{package_version}
**Target Framework:** `net8.0`
**Wave:** `{wave}`

---

## Included Examples

{examples_lines}

---

## Validation Summary

| Stage | Result |
|---|---|
| Capability registry discovery | PASS |
| Example generation | PASS |
| Artifact contract | PASS |
| PR packet assembly | PASS |

---

## Generated By

Pipeline: `lowcode-example-generator` (non-LowCode path)
Discovery: `capability_registry_fallback`
No manual edits. Agent-generated, compiler/runtime approved.
"""

    return PRContent(
        title=title,
        body=body,
        branch=branch,
        labels=["automated", "plugin-examples", family, "non-lowcode"],
        pr_scope_type=PR_SCOPE_PARTIAL_CANARY,
    )
