<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>GenerateBarcodeFromText</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspose.BarCode" Version="26.5.0" />
  </ItemGroup>
</Project>
