"""
Wave 4 dry-run package generator.
Targets: ocr, html, tasks, svg, barcode, imaging, page families.
All packages built under reports/lowcode-plugin-example-factory-parallel-wave-20260605/dryrun/examples/
"""
import json
import pathlib
import subprocess
import sys
import hashlib
import datetime
sys.path.insert(0, str(pathlib.Path(__file__).parents[1] / "src"))

from plugin_examples.plugin_code_registry.loader import PluginCodeRegistryLoader
from plugin_examples.plugin_code_registry.models import PluginEntry
from plugin_examples.example_factory.generator import ExamplePackageGenerator
from plugin_examples.example_factory.templates import FamilyTemplateRegistry, FamilyTemplate, FAMILY_TEMPLATES

REPORT_ROOT = pathlib.Path(__file__).parents[1] / "reports" / "lowcode-plugin-example-factory-parallel-wave-20260605"
DRYRUN_ROOT = REPORT_ROOT / "dryrun" / "examples"
SPRINT = "lowcode-plugin-example-factory-parallel-wave-20260605"

# ── minimal 40x12 white PNG base64 (valid PNG, white pixels, OCR returns empty/trial text) ──
OCR_FIXTURE_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAMCAYAAAAhMsU7AAAAH0lEQVR42mNk+M9QDwAD"
    "hgGAWjR9awAAAABJRU5ErkJggg=="
)

# ── Program.cs content per package ──

PROGRAMS: dict[str, tuple[str, list]] = {
    "ocr/recognize-text": (
        """\
// ocr/recognize-text
// Canonical: https://products.aspose.net/ocr/scanned-image-to-text/
// Package: Aspose.OCR 24.12.0
// Pattern: OcrInput(SingleImage) -> AsposeOcr.Recognize -> RecognitionText
using Aspose.OCR;
using System;
using System.IO;

Directory.CreateDirectory("output");

// Write minimal fixture PNG
byte[] pngBytes = Convert.FromBase64String(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAMCAYAAAAhMsU7AAAAH0lEQVR42mNk+M9QDwAD" +
    "hgGAWjR9awAAAABJRU5ErkJggg==");
string fixturePath = Path.GetFullPath("fixture.png");
File.WriteAllBytes(fixturePath, pngBytes);

var ocr = new AsposeOcr();
var input = new OcrInput(InputType.SingleImage);
input.Add(fixturePath);
var results = ocr.Recognize(input);
string text = results.Count > 0 ? (results[0].RecognitionText ?? "") : "";
string outputText = $"OCR result ({text.Length} chars):\\n{text}\\nFixture: {fixturePath}";
File.WriteAllText("output/result.txt", outputText);
Console.WriteLine($"Recognized: '{text.Trim().Replace("\\n", " ")}'");
Console.WriteLine($"Saved: output/result.txt ({new FileInfo("output/result.txt").Length} bytes)");
""",
        [],
    ),

    "ocr/extract-text": (
        """\
// ocr/extract-text
// Canonical: https://products.aspose.net/ocr/scanned-pdf-to-text/
// Package: Aspose.OCR 24.12.0
// Pattern: OcrInput(SingleImage) -> AsposeOcr.Recognize -> save extracted text
using Aspose.OCR;
using System;
using System.IO;

Directory.CreateDirectory("output");

// Write minimal fixture PNG
byte[] pngBytes = Convert.FromBase64String(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAMCAYAAAAhMsU7AAAAH0lEQVR42mNk+M9QDwAD" +
    "hgGAWjR9awAAAABJRU5ErkJggg==");
string fixturePath = Path.GetFullPath("fixture.png");
File.WriteAllBytes(fixturePath, pngBytes);

var ocr = new AsposeOcr();
var input = new OcrInput(InputType.SingleImage);
input.Add(fixturePath);
var results = ocr.Recognize(input);
string extracted = results.Count > 0 ? (results[0].RecognitionText ?? "") : "";
string report = $"Extracted text length: {extracted.Length}\\nContent:\\n{extracted}\\n";
File.WriteAllText("output/extracted.txt", report);
Console.WriteLine($"Extracted {extracted.Length} chars. Saved to output/extracted.txt ({new FileInfo("output/extracted.txt").Length} bytes)");
""",
        [],
    ),

    "html/convert-html-to-pdf": (
        """\
// html/convert-html-to-pdf
// Canonical: https://products.aspose.net/html/html-to-pdf-converter/
// Package: Aspose.HTML 24.12.0
// Pattern: Converter.ConvertHTML(string, baseUri, PdfSaveOptions, outputPath)
using Aspose.Html;
using Aspose.Html.Converters;
using Aspose.Html.Saving;
using System;
using System.IO;

Directory.CreateDirectory("output");
string outputPath = Path.Combine("output", "output.pdf");

string htmlContent =
    "<!DOCTYPE html><html><head><title>Aspose.HTML Demo</title>" +
    "<style>body{font-family:Arial,sans-serif;margin:40px;}" +
    "h1{color:#2c5f8a;}table{border-collapse:collapse;width:100%;}" +
    "td,th{border:1px solid #ccc;padding:8px;}</style></head><body>" +
    "<h1>HTML to PDF Conversion</h1>" +
    "<p>Generated by Aspose.HTML for .NET on 2026-06-05.</p>" +
    "<table><tr><th>Feature</th><th>Status</th></tr>" +
    "<tr><td>HTML parsing</td><td>Supported</td></tr>" +
    "<tr><td>CSS styling</td><td>Supported</td></tr>" +
    "<tr><td>PDF output</td><td>Supported</td></tr></table>" +
    "</body></html>";

Converter.ConvertHTML(htmlContent, ".", new PdfSaveOptions(), outputPath);
Console.WriteLine($"PDF saved: {outputPath} ({new FileInfo(outputPath).Length} bytes)");
""",
        [],
    ),

    "tasks/convert-mpp-to-pdf": (
        """\
// tasks/convert-mpp-to-pdf
// Canonical: https://products.aspose.net/tasks/project-to-pdf-converter/
// Package: Aspose.Tasks 24.12.0
// Pattern: new Project() -> add tasks -> Save(path, SaveFileFormat.Pdf)
using Aspose.Tasks;
using Aspose.Tasks.Saving;
using System;
using System.IO;

Directory.CreateDirectory("output");
string outputPath = Path.Combine("output", "project.pdf");

var project = new Project();
project.Set(Prj.StartDate, new DateTime(2026, 1, 1));
project.Set(Prj.FinishDate, new DateTime(2026, 12, 31));

var task1 = project.RootTask.Children.Add("Design Phase");
task1.Set(Tsk.Start, new DateTime(2026, 1, 1));
task1.Set(Tsk.Duration, project.GetDuration(5, TimeUnitType.Day));

var task2 = project.RootTask.Children.Add("Development Phase");
task2.Set(Tsk.Start, new DateTime(2026, 1, 8));
task2.Set(Tsk.Duration, project.GetDuration(10, TimeUnitType.Day));

var task3 = project.RootTask.Children.Add("Testing Phase");
task3.Set(Tsk.Start, new DateTime(2026, 1, 22));
task3.Set(Tsk.Duration, project.GetDuration(5, TimeUnitType.Day));

var options = new PdfSaveOptions();
project.Save(outputPath, options);
Console.WriteLine($"Project PDF saved: {outputPath} ({new FileInfo(outputPath).Length} bytes)");
""",
        [],
    ),

    "svg/svg-to-image-converter": (
        """\
// svg/svg-to-image-converter
// Canonical: https://products.aspose.net/svg/svg-to-image-converter/
// Package: Aspose.SVG 24.12.0
// Pattern: SVGDocument -> Converter.ConvertSVG(doc, ImageSaveOptions(PNG), outputPath)
using Aspose.Svg;
using Aspose.Svg.Converters;
using Aspose.Svg.Saving;
using Aspose.Svg.Rendering.Image;
using System;
using System.IO;

Directory.CreateDirectory("output");
string outputPath = Path.Combine("output", "output.png");

string svgContent =
    @"<svg xmlns=""http://www.w3.org/2000/svg"" width=""400"" height=""300"">" +
    @"<rect width=""400"" height=""300"" fill=""#f0f8ff""/>" +
    @"<rect x=""20"" y=""20"" width=""360"" height=""260"" rx=""15"" fill=""#4a90d9"" opacity=""0.85""/>" +
    @"<circle cx=""200"" cy=""130"" r=""60"" fill=""white"" opacity=""0.9""/>" +
    @"<text x=""200"" y=""140"" text-anchor=""middle"" font-size=""28"" fill=""#4a90d9"" font-family=""Arial"">SVG</text>" +
    @"<text x=""200"" y=""250"" text-anchor=""middle"" font-size=""16"" fill=""white"">Image Converter</text>" +
    @"</svg>";

using var document = new SVGDocument(svgContent, ".");
var imageOptions = new ImageSaveOptions(ImageFormat.Png);
Converter.ConvertSVG(document, imageOptions, outputPath);
Console.WriteLine($"PNG saved: {outputPath} ({new FileInfo(outputPath).Length} bytes)");
""",
        [],
    ),

    "barcode/generate-barcode": (
        """\
// barcode/generate-barcode
// Canonical: https://products.aspose.net/barcode/1d-barcode-writer/
// Package: Aspose.BarCode 24.12.0
// Pattern: new BarcodeGenerator(EncodeTypes.Code128, data) -> Save(path, PNG)
using Aspose.BarCode.Generation;
using System;
using System.IO;

Directory.CreateDirectory("output");
string outputPath = Path.Combine("output", "barcode.png");

using (var gen = new BarcodeGenerator(EncodeTypes.Code128, "ASPOSE-BARCODE-2026"))
{
    gen.Parameters.Barcode.XDimension.Pixels = 3;
    gen.Parameters.Barcode.BarHeight.Pixels = 100;
    gen.Save(outputPath, BarCodeImageFormat.Png);
}
Console.WriteLine($"1D barcode generated: {outputPath} ({new FileInfo(outputPath).Length} bytes)");
""",
        [],
    ),

    "barcode/recognize-barcode": (
        """\
// barcode/recognize-barcode
// Canonical: https://products.aspose.net/barcode/1d-barcode-reader/
// Package: Aspose.BarCode 24.12.0
// Pattern: BarcodeGenerator(Code128) -> Save PNG -> BarCodeReader(PNG, Code128) -> ReadBarCodes
using Aspose.BarCode.Generation;
using Aspose.BarCode.BarCodeRecognition;
using System;
using System.IO;
using System.Text;

Directory.CreateDirectory("output");

// Generate fixture barcode image
string fixturePath = "fixture_barcode.png";
using (var gen = new BarcodeGenerator(EncodeTypes.Code128, "RECOGNITION-TEST-2026"))
{
    gen.Parameters.Barcode.XDimension.Pixels = 3;
    gen.Save(fixturePath, BarCodeImageFormat.Png);
}

// Recognize the barcode
var sb = new StringBuilder();
using (var reader = new BarCodeReader(fixturePath, DecodeType.Code128))
{
    foreach (var result in reader.ReadBarCodes())
    {
        string line = $"Type={result.CodeType}, Value={result.CodeText}";
        Console.WriteLine(line);
        sb.AppendLine(line);
    }
}
File.WriteAllText("output/result.txt", sb.ToString());
Console.WriteLine($"Recognition complete. Output/result.txt: {new FileInfo("output/result.txt").Length} bytes");
""",
        [],
    ),

    "imaging/convert-image": (
        """\
// imaging/convert-image
// Canonical: https://products.aspose.net/imaging/image-converter/
// Package: Aspose.Imaging 24.12.0
// Pattern: Create BMP -> Save as PNG (format conversion)
using Aspose.Imaging;
using Aspose.Imaging.Brushes;
using Aspose.Imaging.ImageOptions;
using System;
using System.IO;

Directory.CreateDirectory("output");
string outputPath = Path.Combine("output", "converted.png");

using (var bmp = new Aspose.Imaging.FileFormats.Bmp.BmpImage(200, 200))
{
    var graphics = new Graphics(bmp);
    graphics.Clear(Color.FromArgb(255, 245, 250, 255));

    // Blue filled rectangle
    graphics.FillRectangle(
        new SolidBrush(Color.FromArgb(255, 74, 144, 217)),
        new Rectangle(20, 20, 160, 80));

    // White filled rectangle (inner)
    graphics.FillRectangle(
        new SolidBrush(Color.White),
        new Rectangle(40, 40, 120, 40));

    // Green ellipse
    graphics.FillEllipse(
        new SolidBrush(Color.FromArgb(255, 80, 200, 120)),
        new Rectangle(60, 130, 80, 50));

    bmp.Save(outputPath, new PngOptions());
}
Console.WriteLine($"Converted BMP->PNG: {outputPath} ({new FileInfo(outputPath).Length} bytes)");
""",
        [],
    ),

    "imaging/compress-image": (
        """\
// imaging/compress-image
// Canonical: https://products.aspose.net/imaging/image-compressor/
// Package: Aspose.Imaging 24.12.0
// Pattern: Create BMP -> Save as JPEG with quality=75 (compression)
using Aspose.Imaging;
using Aspose.Imaging.Brushes;
using Aspose.Imaging.ImageOptions;
using System;
using System.IO;

Directory.CreateDirectory("output");
string outputPath = Path.Combine("output", "compressed.jpg");

using (var bmp = new Aspose.Imaging.FileFormats.Bmp.BmpImage(400, 300))
{
    var graphics = new Graphics(bmp);
    graphics.Clear(Color.FromArgb(255, 240, 248, 255));

    // Draw layered rectangles for visual interest
    int[] r = {200, 100, 150, 80, 120};
    int[] g = {60,  180,  40, 220,  90};
    int[] b = {60,   60, 200,  60, 190};
    for (int i = 0; i < 5; i++)
    {
        graphics.FillRectangle(
            new SolidBrush(Color.FromArgb(255, (byte)r[i], (byte)g[i], (byte)b[i])),
            new Rectangle(20 + i * 60, 30 + i * 30, 150, 80));
    }

    // Save as JPEG quality 75 — compress relative to BMP source
    bmp.Save(outputPath, new JpegOptions { Quality = 75 });
}
long size = new FileInfo(outputPath).Length;
Console.WriteLine($"Compressed JPEG (q=75): {outputPath} ({size} bytes)");
""",
        [],
    ),

    "page/convert-xps-to-pdf": (
        """\
// page/convert-xps-to-pdf
// Canonical: https://products.aspose.net/page/xps-converter/
// Package: Aspose.Page 24.12.0
// Pattern: Create XpsDocument -> AddPath -> Save XPS -> Load XPS -> PdfDevice -> Save PDF
using Aspose.Page.XPS;
using Aspose.Page.XPS.XpsModel;
using Aspose.Page.XPS.Presentation.Pdf;
using System;
using System.IO;

Directory.CreateDirectory("output");
string xpsPath = "fixture.xps";
string outputPath = Path.Combine("output", "output.pdf");

// Step 1: Create a minimal XPS document programmatically
using (var xpsDoc = new XpsDocument())
{
    // Add a page with a simple colored path
    XpsPath path = xpsDoc.AddPath(xpsDoc.CreatePathGeometry("M 30,20 L 300,20 L 300,100 L 30,100 Z"));
    path.Fill = xpsDoc.CreateSolidColorBrush(xpsDoc.CreateColor(0.2f, 0.5f, 0.8f));

    XpsPath path2 = xpsDoc.AddPath(xpsDoc.CreatePathGeometry("M 50,130 L 280,130 L 280,180 L 50,180 Z"));
    path2.Fill = xpsDoc.CreateSolidColorBrush(xpsDoc.CreateColor(0.8f, 0.3f, 0.2f));

    xpsDoc.Save(xpsPath);
    Console.WriteLine($"XPS fixture created: {xpsPath}");
}

// Step 2: Convert XPS to PDF
using (var xps = new XpsDocument(xpsPath, new XpsLoadOptions()))
{
    var pdfOptions = new PdfSaveOptions();
    using (var outStream = new FileStream(outputPath, FileMode.Create))
    {
        xps.Save(new PdfDevice(outStream, pdfOptions));
    }
}
Console.WriteLine($"PDF saved: {outputPath} ({new FileInfo(outputPath).Length} bytes)");
""",
        [],
    ),
}

FAMILY_PACKAGE_MAP = {
    "barcode": "Aspose.BarCode",
    "imaging": "Aspose.Imaging",
    "zip": "Aspose.ZIP",
    "html": "Aspose.HTML",
    "tasks": "Aspose.Tasks",
    "svg": "Aspose.SVG",
    "tex": "Aspose.TeX",
    "ocr": "Aspose.OCR",
    "psd": "Aspose.PSD",
    "cad": "Aspose.CAD",
    "page": "Aspose.Page",
}

CSPROJ_TEMPLATE = """\
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="{PACKAGE}" Version="{VERSION}" />
  </ItemGroup>
</Project>
"""

NUGET_VERSIONS = {
    "Aspose.BarCode": "24.12.0",
    "Aspose.Imaging": "24.12.0",
    "Aspose.ZIP": "24.12.0",
    "Aspose.HTML": "24.12.0",
    "Aspose.Tasks": "24.12.0",
    "Aspose.SVG": "24.12.0",
    "Aspose.TeX": "24.12.0",
    "Aspose.OCR": "24.12.0",
    "Aspose.PSD": "24.12.0",
    "Aspose.CAD": "24.12.0",
    "Aspose.Page": "24.12.0",
}


def run_cmd(cmd, cwd, timeout=180):
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=str(cwd), timeout=timeout)
    return proc.returncode, proc.stdout + proc.stderr


def generate_and_build(key: str, program_cs: str, extra_packages: list) -> dict:
    family, slug = key.split("/")
    pkg_dir = DRYRUN_ROOT / family / slug
    pkg_dir.mkdir(parents=True, exist_ok=True)
    (pkg_dir / "output").mkdir(exist_ok=True)

    pkg_name = FAMILY_PACKAGE_MAP[family]
    version = NUGET_VERSIONS[pkg_name]

    # Write csproj
    csproj = CSPROJ_TEMPLATE.format(PACKAGE=pkg_name, VERSION=version)
    (pkg_dir / f"{family}-{slug}.csproj").write_text(csproj)

    # Write Program.cs
    (pkg_dir / "Program.cs").write_text(program_cs, encoding="utf-8")

    # Write README
    readme = f"# {family}/{slug}\n\n**Package**: {pkg_name} {version}\n\n## Run\n\n```bash\ndotnet restore\ndotnet build\ndotnet run\n```\n\nOutput will be in `output/`.\n"
    (pkg_dir / "README.md").write_text(readme)

    # Write source-provenance
    provenance = {
        "family": family,
        "plugin_slug": slug,
        "nuget_package": pkg_name,
        "nuget_version": version,
        "sprint": SPRINT,
        "generated_at": "2026-06-05",
    }
    (pkg_dir / "source-provenance.json").write_text(json.dumps(provenance, indent=2))

    # Build + run
    result = {"key": key, "pkg_dir": str(pkg_dir)}
    for step, cmd in [("restore", ["dotnet", "restore"]), ("build", ["dotnet", "build"]), ("run", ["dotnet", "run"])]:
        rc, log = run_cmd(cmd, pkg_dir)
        (pkg_dir / f"{step}.log").write_text(log)
        result[step] = {"exit_code": rc, "status": "SUCCESS" if rc == 0 else "FAILED"}
        if rc != 0 and step != "run":
            result["verdict"] = f"{step.upper()}_FAILED"
            result["error_snippet"] = log[-800:]
            break
    else:
        output_dir = pkg_dir / "output"
        output_files = [
            {"path": str(f.relative_to(pkg_dir)), "size": f.stat().st_size}
            for f in output_dir.iterdir() if f.is_file()
        ] if output_dir.exists() else []
        has_output = any(o["size"] > 0 for o in output_files)
        run_ok = result.get("run", {}).get("exit_code", 1) == 0
        result["verdict"] = "PASS" if (run_ok and has_output) else ("RUN_FAILED" if not run_ok else "OUTPUT_MISSING")
        result["output_files"] = output_files

        # Write output-validation
        (pkg_dir / "output-validation.json").write_text(json.dumps({
            "package": key,
            "restore_status": result["restore"]["status"],
            "build_status": result["build"]["status"],
            "run_status": result["run"]["status"],
            "output_files": output_files,
            "verdict": result["verdict"],
            "validated_at": "2026-06-05",
        }, indent=2))

    return result


def main():
    print(f"Wave 4 package generation — {len(PROGRAMS)} packages")
    DRYRUN_ROOT.mkdir(parents=True, exist_ok=True)
    results = []

    for key, (program_cs, extra_packages) in PROGRAMS.items():
        print(f"\n=== {key} ===")
        try:
            r = generate_and_build(key, program_cs, extra_packages)
            results.append(r)
            verdict = r.get("verdict", "?")
            print(f"  verdict: {verdict}")
            if verdict != "PASS":
                snippet = r.get("error_snippet", "")
                if snippet:
                    print(f"  error: {snippet[-300:]}")
            else:
                for f in r.get("output_files", []):
                    print(f"  output: {f['path']} ({f['size']} bytes)")
        except Exception as e:
            print(f"  EXCEPTION: {e}")
            results.append({"key": key, "verdict": "EXCEPTION", "error": str(e)})

    # Write manifest
    manifest = {
        "sprint": SPRINT,
        "generated_at": "2026-06-05",
        "total": len(results),
        "passed": sum(1 for r in results if r.get("verdict") == "PASS"),
        "failed": sum(1 for r in results if r.get("verdict") != "PASS"),
        "results": results,
    }
    out_path = REPORT_ROOT / "dryrun" / "wave4-build-results.json"
    out_path.write_text(json.dumps(manifest, indent=2))
    print(f"\n=== SUMMARY: {manifest['passed']}/{manifest['total']} PASS ===")
    print(f"Results: {out_path}")
    return manifest


if __name__ == "__main__":
    main()
