#!/usr/bin/env python3
"""Sync open-taskcard-closure-matrix.json to docs/discovery/open-taskcard-closure-matrix.md.

Reads the authoritative JSON matrix and regenerates the markdown table.
Run this after any taskcard update to keep JSON and MD in sync.

Usage:
    python scripts/sync_taskcards.py [--check]

    --check: Verify MD is in sync with JSON (exit 1 if not, 0 if in sync)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MATRIX_JSON = REPO_ROOT / "workspace" / "verification" / "latest" / "open-taskcard-closure-matrix.json"
MATRIX_MD = REPO_ROOT / "docs" / "discovery" / "open-taskcard-closure-matrix.md"


def _load_matrix() -> dict:
    """Load the taskcard matrix from JSON."""
    if not MATRIX_JSON.exists():
        raise FileNotFoundError(f"Taskcard matrix not found: {MATRIX_JSON}")
    return json.loads(MATRIX_JSON.read_text(encoding="utf-8", errors="replace"))


def _render_markdown(matrix: dict) -> str:
    """Render the taskcard matrix as a markdown document."""
    taskcards: list[dict] = matrix.get("taskcards", [])
    matrix_date: str = matrix.get("matrix_date", "unknown")
    sprint: str = matrix.get("sprint", "")

    open_tcs = [tc for tc in taskcards if tc.get("status") == "OPEN"]
    closed_tcs = [tc for tc in taskcards if tc.get("status") not in ("OPEN",)]

    lines: list[str] = [
        f"# Open Taskcard Closure Matrix",
        f"",
        f"**Last updated:** {matrix_date}  ",
        f"**Sprint:** {sprint}  ",
        f"**Total:** {len(taskcards)} | **Open:** {len(open_tcs)} | **Closed:** {len(closed_tcs)}",
        f"",
        f"> Generated by `scripts/sync_taskcards.py` from `workspace/verification/latest/open-taskcard-closure-matrix.json`.",
        f"> Do not edit this file directly — edit the JSON and re-run the sync script.",
        f"",
    ]

    # Open taskcards table
    lines += [
        f"## Open Taskcards ({len(open_tcs)})",
        f"",
        f"| ID | Title | Blocking |",
        f"|---|---|---|",
    ]
    for tc in open_tcs:
        tc_id = tc.get("id", "")
        title = tc.get("title", "")
        blocking = tc.get("blocking", "") or ""
        # Escape pipe chars in title
        title_safe = title.replace("|", "\\|")
        blocking_safe = str(blocking).replace("|", "\\|") if blocking else "—"
        lines.append(f"| `{tc_id}` | {title_safe} | {blocking_safe} |")

    lines += [""]

    # Closed taskcards summary
    lines += [
        f"## Closed Taskcards ({len(closed_tcs)})",
        f"",
        f"| ID | Status | Closed In |",
        f"|---|---|---|",
    ]
    for tc in closed_tcs:
        tc_id = tc.get("id", "")
        status = tc.get("status", "")
        closed_in = tc.get("closed_in", "") or "—"
        closed_in_safe = str(closed_in).replace("|", "\\|")
        lines.append(f"| `{tc_id}` | {status} | {closed_in_safe} |")

    lines += ["", ""]
    return "\n".join(lines)


def sync(check_only: bool = False) -> int:
    """Sync or check the taskcard matrix markdown.

    Returns:
        0 if success / in-sync, 1 if out-of-sync (check mode) or error.
    """
    try:
        matrix = _load_matrix()
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    rendered = _render_markdown(matrix)

    if check_only:
        if not MATRIX_MD.exists():
            print("OUT OF SYNC: Markdown file does not exist.", file=sys.stderr)
            return 1
        existing = MATRIX_MD.read_text(encoding="utf-8")
        if existing.strip() == rendered.strip():
            print("IN SYNC: open-taskcard-closure-matrix.md matches JSON matrix.")
            return 0
        else:
            print("OUT OF SYNC: open-taskcard-closure-matrix.md differs from JSON matrix.", file=sys.stderr)
            print("Run: python scripts/sync_taskcards.py  to update.", file=sys.stderr)
            return 1
    else:
        MATRIX_MD.parent.mkdir(parents=True, exist_ok=True)
        MATRIX_MD.write_text(rendered, encoding="utf-8")
        taskcards = matrix.get("taskcards", [])
        open_count = sum(1 for tc in taskcards if tc.get("status") == "OPEN")
        print(f"Synced: {len(taskcards)} taskcards ({open_count} open) -> {MATRIX_MD}")
        return 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Check if MD is in sync with JSON (exit 1 if not)")
    args = parser.parse_args()
    sys.exit(sync(check_only=args.check))


if __name__ == "__main__":
    main()
