<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>FinanceConvertxbrl</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspose.Finance" Version="24.12.0" />
  </ItemGroup>
</Project>
