// page/ps-converter
// Canonical: https://products.aspose.net/page/ps-converter/
// Package: Aspose.Page 24.12.0
// Pattern: Embed PS fixture -> PsDocument(stream) -> SaveAsPdf(outStream, PdfSaveOptions)
using Aspose.Page.EPS;
using Aspose.Page.EPS.Device;
using System;
using System.IO;

Directory.CreateDirectory("output");
string outputPath = Path.Combine("output", "output.pdf");

// Embedded minimal PostScript document (base64)
string psBase64 = Convert.ToBase64String(System.Text.Encoding.ASCII.GetBytes(
    "%!PS-Adobe-3.0\n" +
    "%%Title: Aspose.Page PS Converter Demo\n" +
    "%%Creator: fixture factory\n" +
    "%%Pages: 1\n" +
    "%%BoundingBox: 0 0 595 842\n" +
    "%%EndComments\n" +
    "%%Page: 1 1\n" +
    "/Helvetica findfont 24 scalefont setfont\n" +
    "72 750 moveto\n" +
    "(Aspose.Page PS Converter Demo) show\n" +
    "/Helvetica findfont 14 scalefont setfont\n" +
    "72 720 moveto\n" +
    "(Generated by the fixture factory for dry-run testing.) show\n" +
    "showpage\n" +
    "%%EOF\n"
));

byte[] psBytes = Convert.FromBase64String(psBase64);
string fixturePath = "fixture.ps";
File.WriteAllBytes(fixturePath, psBytes);

var pdfSaveOptions = new PdfSaveOptions();
using (FileStream psStream = new FileStream(fixturePath, FileMode.Open))
using (FileStream pdfStream = new FileStream(outputPath, FileMode.Create))
{
    var psDoc = new PsDocument(psStream);
    psDoc.SaveAsPdf(pdfStream, pdfSaveOptions);
}

long size = new FileInfo(outputPath).Length;
Console.WriteLine($"PS converted to PDF: {outputPath} ({size} bytes)");
